name: "Build ubuntu image and rootfs"
author: "https://github.com/ophub/flippy-ubuntu-actions"
description: "Ubuntu Image Builder"
inputs:
  mode:
    description: "Select script."
    required: false
    default: "flippy"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        cd "${GITHUB_ACTION_PATH}"
        ./make_actions.sh

branding:
  icon: "terminal"
  color: "gray-dark"
