name: "Build Ubuntu image and rootfs for Rockchip devices"
author: "https://github.com/ophub/flippy-ubuntu-actions"
description: "Build Ubuntu/Debian system images and rootfs for Rockchip series devices."
inputs:
  mode:
    description: "Select the build script to use."
    required: false
    default: "flippy"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        cd "${GITHUB_ACTION_PATH}"
        ./make_actions.sh

branding:
  icon: "terminal"
  color: "gray-dark"
