pcm.mic4 {
    type plug
    slave {
        pcm "hw:0,0"
        channels 4
        rate 16000
        format S16_LE
    }
}

pcm.main_mic0 {
    type route
    slave.pcm "mic4"
    slave.channels 4
    ttable {
        0.0 16.0
        1.0 16.0
    }
}

pcm.playback {
    type plug
    slave.pcm "speaker_downmix"
    slave.channels 2
}

# 扬声器只有右声道，L + R 混合到右声道
pcm.speaker_downmix {
    type route
    slave.pcm "hw:0,0"
    slave.channels 2
    ttable {
        0.1 1.0
        1.1 1.0
    }
}

pcm.!default {
    type asym
    playback.pcm "playback"
    capture.pcm "main_mic0"
}
