#####################################################################################
# DO NOT EDIT THIS FILE                                                             #
#                                                                                   #
# Please edit /boot/bootEnv.txt or /boot/armbianEnv.txt to set supported parameters #
# Recompile with:                                                                   #
# mkimage -C none -A arm -T script -n 'flatmax load script' -d boot.cmd boot.scr    #
#                                                                                   #
#####################################################################################

# default values
setenv load_addr "0x09000000"
setenv overlay_error "false"
setenv rootdev "/dev/mmcblk0p1"
setenv verbosity "1"
setenv console "both"
setenv bootlogo "false"
setenv rootfstype "ext4"
setenv rootflags "rw,errors=remount-ro"
setenv docker_optimizations "on"
setenv earlycon "off"

if test -z "${distro_bootpart}"; then setenv distro_bootpart 1; fi

setenv prefix "/"
if test -e ${devtype} ${devnum}:${distro_bootpart} /boot/bootEnv.txt; then setenv prefix "/boot/"; fi
if test -e ${devtype} ${devnum}:${distro_bootpart} /boot/armbianEnv.txt; then setenv prefix "/boot/"; fi
echo "Booting from ${devtype} ${devnum}:${distro_bootpart} with prefix ${prefix}"

if load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}bootEnv.txt || load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}armbianEnv.txt; then
    env import -t ${load_addr} ${filesize}
    echo "The env file loaded from ${devtype} ${devnum}:${distro_bootpart}"
else
    echo "No env file found, using defaults."
fi

if test "${logo}" = "disabled"; then setenv logo "logo.nologo"; fi
if test "${console}" = "display" || test "${console}" = "both"; then setenv consoleargs "console=tty1"; fi
if test "${console}" = "serial" || test "${console}" = "both"; then setenv consoleargs "${consoleargs}"; fi
if test "${earlycon}" = "on"; then setenv consoleargs "${earlyconargs} ${consoleargs}"; fi

if test "${bootlogo}" = "true"; then
    setenv consoleargs "splash plymouth.ignore-serial-consoles ${consoleargs}"
fi

# get PARTUUID of first partition on SD/eMMC the boot script was loaded from
if test "${devtype}" = "mmc"; then part uuid mmc ${devnum}:${distro_bootpart} partuuid; fi

setenv bootargs "root=${rootdev} rootwait rootfstype=${rootfstype} rootflags=${rootflags} ${consoleargs} consoleblank=0 loglevel=${verbosity} ubootpart=${partuuid} usb-storage.quirks=${usbstoragequirks} ${extraargs} ${extraboardargs}"

if test "${docker_optimizations}" = "on"; then setenv bootargs "${bootargs} cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1"; fi

echo "INITRAMFS: uInitrd loading ..."
load ${devtype} ${devnum}:${distro_bootpart} ${ramdisk_addr_r} ${prefix}uInitrd
if test -e ${devtype} ${devnum}:${distro_bootpart} ${kernel_addr_r} ${prefix}zImage; then
    echo "KERNEL: zImage loading ..."
    load ${devtype} ${devnum}:${distro_bootpart} ${kernel_addr_r} ${prefix}zImage
elif test -e ${devtype} ${devnum}:${distro_bootpart} ${kernel_addr_r} ${prefix}Image; then
    echo "KERNEL: Image loading ..."
    load ${devtype} ${devnum}:${distro_bootpart} ${kernel_addr_r} ${prefix}Image
fi

echo "fdtfile: ${prefix}dtb/${fdtfile} loading ..."
load ${devtype} ${devnum}:${distro_bootpart} ${fdt_addr_r} ${prefix}dtb/${fdtfile}
fdt addr ${fdt_addr_r}
fdt resize 131072

for overlay_file in ${overlays}; do
    if load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}dtb/rockchip/overlay/${overlay_prefix}-${overlay_file}.dtbo; then
        echo "Applying kernel provided DT overlay ${overlay_prefix}-${overlay_file}.dtbo"
        fdt apply ${load_addr} || setenv overlay_error "true"
    elif load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}dtb/rockchip/overlay/${overlay_file}.dtbo; then
        echo "Applying kernel provided DT overlay ${overlay_file}.dtbo"
        fdt apply ${load_addr} || setenv overlay_error "true"
    fi
done
for overlay_file in ${user_overlays}; do
    if load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}overlay-user/${overlay_file}.dtbo; then
        echo "Applying user provided DT overlay ${overlay_file}.dtbo"
        fdt apply ${load_addr} || setenv overlay_error "true"
    fi
done

if test "${overlay_error}" = "true"; then
    echo "Error applying DT overlays, restoring original DT"
    load ${devtype} ${devnum}:${distro_bootpart} ${fdt_addr_r} ${prefix}dtb/${fdtfile}
else
    if test -e ${devtype} ${devnum}:${distro_bootpart} ${prefix}dtb/rockchip/overlay/${overlay_prefix}-fixup.scr; then
        load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}dtb/rockchip/overlay/${overlay_prefix}-fixup.scr
        echo "Applying kernel provided DT fixup script (${overlay_prefix}-fixup.scr)"
        source ${load_addr}
    fi
    if test -e ${devtype} ${devnum}:${distro_bootpart} ${prefix}fixup.scr; then
        load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}fixup.scr
        echo "Applying user provided fixup script (fixup.scr)"
        source ${load_addr}
    fi
fi

booti ${kernel_addr_r} ${ramdisk_addr_r} ${fdt_addr_r}
